appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: q8AYbhwruWsbuNZmimR2UpnQxHMx21kdmBQqBnBcyJ+Tgl7lpofzMUaYWyNSLdqiVPh66gssvY67wdDikxF7nBCqf+boENlHHseqkbbofRSIuUkPsYHZd9asOPuDBeV6oZcUSZi+AvyQzA/u8J47UrALcvVozSO5nl9B21QtQd4v5h0sklAn1J1bk4ZRXqaxo+bh7xSsTDXrJa1WcPob1JdeQKi3eavrREaVgSoHy+PM752CHELz84R5YGo90zkE9mDHiMl8fcC4JhWVdCI6UbpAM+dJ/Cz171X0NrOKLAR56eOBCQ97KcZYS1WFBzr9TTXZmK5N+wLEXWtrrueFEmqGZk7ckJmLdsb1PDIAPQR7HYJe235auekLDpSF0OwqW6GNVvtiuWuBS6jzjJazwAlL49VYI2rr01GuFReRFAp73d1NVSyApoTjSggLo5rk86A5auDSeOYFvuNYPxydANr1JiNC3x+by5Nbt2AGESywCKM+wlaVBT5WM/LZWeJ5CVLbxrwHi5JZ4q2oXoopaCCwOgwVQpMNN2w+4ZQC9PeK0S6ivuYmk8LmvvDo0/k7hi9kjAkH7hmAERVgF6a84b2d/h35U2hY2iFyBcZX4B97+Amu7MKYo4LX/VJgSM9uusAiFs14qQ/C6krudmnsRoaK71QVpNJiNmxChFymSv4=}
bot:
  automerge: true
